version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongo_data:/data/db

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379

  neo4j:
   image: neo4j:5.3
   restart: unless-stopped
   ports:
     - 7474:7474
     - 7687:7687
   volumes:
     - ./neo4j/conf:/conf
     - ./neo4j/data:/data
     - ./neo4j/import:/import
     - ./neo4j/logs:/logs
     - ./neo4j/plugins:/plugins
   environment: 
     - NEO4J_AUTH=neo4j/mypassword
     # Raise memory limits
     - NEO4J_dbms_memory_pagecache_size=1G
     - NEO4J_dbms.memory.heap.initial_size=1G
     - NEO4J_dbms_memory_heap_max__size=1G
     - NEO4J_dbms_security_procedures_unrestricted=gds.*

  webapp:
    image: mq37/nosql-webapp
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - neo4j
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - mongo_host=mongo
      - redis_host=redis
      - neo4j_host=neo4j
